baseURL = 'https://blog.maxfrancis.me/'
languageCode = 'en-us'
title = 'Maxwell Francis'
themesDir = 'themes'
theme = "archie"
[caches]
  [caches.images]
    dir = ':cacheDir/images'

[[menu.main]]
name = "Book a Cyber Consultation (Free)"
url = "https://calendar.proton.me/bookings#NUSArp84rs7bHHphZNLDJKcWDa-Y8ThDPG_4usR0irQ="
weight = 1

[[menu.main]]
name = "Blog"
url = "/"
weight = 2

[[menu.main]]
name = "About"
url = "/about/"
weight = 3